ktor {
    deployment {
        port = 8080
        port = ${?PORT} # Se esiste la variabile d'ambiente PORT, usa quella
    }
    application {
        modules = [ it.fraudata.ServerKt.module ]
    }
}

fraudgen {
    kafka {
        bootstrapServers = "localhost:9092"
        bootstrapServers = ${?KAFKA_BOOTSTRAP_SERVERS}
        topic = "transactions"
    }
    api {
        swaggerFile = "openapi.yml"
    }
    storage {
        driver = "org.postgresql.Driver"
        jdbcUrl = "jdbc:postgresql://localhost:5432/fraudgen_db"
        jdbcUrl = ${?DB_URL}
        user = "frauduser"
        user = ${?DB_USER}
        password = "fraudpass"
        password = ${?DB_PASSWORD}
    }
    security {
        apiKey = "default-dev-key" # Fallback per sviluppo se manca il .env
        apiKey = ${?API_SECRET_KEY}
    }
}