openapi: "3.0.0"
info:
  title: "FrauData Generator API"
  version: "1.0.0"
  description: "REST API to generate synthetic banking data for ML and testing purposes."

paths:
  /api/v1/stream:
    post:
      summary: "Start a live stream of transactions to Kafka"
      security:
        - bearerAuth: []
      description: "Generates data and streams it in background mimicking real-time TPS."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/StreamRequest"
      responses:
        "202":
          description: "Stream accepted and processing in background"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StreamResponse"

  /api/v1/generate:
    post:
      summary: "Generate synthetic accounts and transactions"
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GenerationRequest"
      responses:
        "200":
          description: "Data successfully generated"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenerationResponse"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: API Key
  schemas:
    StreamRequest:
      type: object
      properties:
        accountsCount:
          type: integer
          example: 2
        countryCode:
          type: string
          example: "GB"
        transactionsPerAccount:
          type: integer
          example: 50
        persona:
          type: string
          enum: [Salaryman, Student, Gambler]
          example: "Gambler"
        tps:
          type: integer
          example: 5
          
    StreamResponse:
      type: object
      properties:
        message:
          type: string
        status:
          type: string
        estimatedCompletionSeconds:
          type: integer
          
    GenerationRequest:
      type: object
      properties:
        accountsCount:
          type: integer
          example: 5
        countryCode:
          type: string
          example: "GB"
        transactionsPerAccount:
          type: integer
          example: 20
        persona:
          type: string
          enum: [Salaryman, Student, Gambler]
          example: "Student"
          
    GenerationResponse:
      type: object
      properties:
        message:
          type: string
        totalAccounts:
          type: integer
        totalTransactions:
          type: integer
